name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file cheers2019/Dockerfile --tag aleguerra05/cheers2019:$(date +%s)
           
